name: CI

on:
  push:
    branches:
      - front

jobs:
  merge_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to dev
        run: |
          git config user.name "ahyeon"
          git config user.email "ahoney@gmail.com"
          git checkout dev
          git merge --no-ff ${{ github.event.after }}
          git push

      - name: Cleanup
        run: git checkout front
